### ISSUE TITLE
Use `nmea_plus` gem for parser implementation?

### ISSUE THREAD

**Issue by ianfixes** [jamesduncombe/gps-parser#1]
I'm the maintainer of the [`nmea_plus` ruby gem](https://github.com/ianfixes/nmea_plus) (a parsing library for GPS messages), and I do periodic google searches to see what alternatives exist -- this project came up.  Could my project help yours get to completion?

**Comment by jamesduncombe** [comment]
Hi Ian, thanks for getting in touch! To be honest, I haven't carried out any work on this project for a long long time and am unlikely to do so. I've had a look at your gem, it looks awesome and it's certainly something I'd consider using in the future :)

**Comment by ianfixes** [comment]
OK, I'd be glad to help in any way that I can

**Comment by jamesduncombe** [comment]
Thanks Ian, most appreciated
